"""create message table

Revision ID: dbf42e5cf177
Revises: 
Create Date: 2016-08-24 16:40:44.534473

"""

# revision identifiers, used by Alembic.
revision = 'dbf42e5cf177'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('uuid', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('receiver', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('flag', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    ### end Alembic commands ###
